### ISSUE TITLE
goals for 2.0

### ISSUE THREAD

**Issue by falcoraptor** [ThematicTheme/Thematic#52]
- [x] #59 convert commentform to html5
- [x] #50 update html ID's to classes 
- [x] convert to html5 markup -- [pull request #67] 
- [x] #60 convert comments callback to html5 -- [pull request #69 ]
- [x] #51 add html5shiv for older browsers -- [pull request #68]
- [x] #56 integrate with theme customizer
- [x] #61 create a new stylesheet for the new markup
- [x] add media queries to new stylesheet

**Comment by JamesGeiger** [comment]
@middlesister Any chance we can include the following?
1. Integrate breadcrumbs into the theme. Totally optional via add_theme_support. Hybrid Core has an extension that works as a standalone script. We can use that.
2. Pagination. Totally optional via add_theme_support. Also see Hybrid Core for that. I do not like using a plugin for pagination.
3. Remove all widgets except the footer and primary sidebar widgets. The rest can be optionally added via add_theme_support.

P.S. I am more of a front-end person, so tell me what to do in regards to the style and I will do it. I think we should gut all the styles and add a few staples like normalize.css, etc. These will be loaded via add_theme_support. While it seems like we will use add_theme_support a lot if we implement all the above, but it is how it is done in Hybrid Core. I keep saying Hybrid Core because the guy who makes it is perhaps the best coder I know and has the best knowledge of WordPress.

P.P.S. I just got a 6 month contract extension for my job, and it is only 35 hrs a week, so I have time to help now.

**Comment by falcoraptor** [comment]
That's great, now is a perfect time to help!

I think all of these are good ideas, but something to consider for 2.1

I would like to get 2.0 out before the end of january and if we keep adding features, we will never get it out in the first place. The changelog will be big enough as it is :)

We have styling and testing left to do for 2.0. We also need to update the pot file in time for translators to update their translations in glotpress. And I would like to have some documentation written when the release drops so users have a clue on all the changes without having to read the code themselves.

Create an issue for each of these things and I'll add them to the 2.1 milestone.

**Comment by JamesGeiger** [comment]
OK I will.

One question, how will users upgrade? Will they have to click an checkbox to upgrade in the options page?

P.S. I am sending you an email about something. Let me know your thoughts. (It related to Thematic).

**Comment by JamesGeiger** [comment]
@middlesister  Oh one more note before I open up some issues. Is there anyway we can get rid of blog-title and convert to site-title? Blog-title almost has a negative connotation because it makes it seem like your site is limited to a blog.

**Comment by falcoraptor** [comment]
As I think you've seen, .site-title has already been added as a class to that div. 
The id `blog-title` will not be removed from the markup because of backwards compatibility, but it will not be used in the new css.

And yes, there is a checkbox in the theme options page to enable/disable the legacy mode. I think the feature is incomplete and needs some bugs to be ironed out, but it's basically there.

**Comment by JamesGeiger** [comment]
Cool :)

The blog-title is not a big deal. I can filter it anyway.

**Comment by JamesGeiger** [comment]
@middlesister I have done a search for a while and really did not find any good Superfish alternative. I think it is fine if we keep it. I _actually_ like it, because it is hard to achieve some of it's drop-down effects in pure css3.

Also, should we just rename Style1.css to Style.css? It seems cleaner.

**Comment by falcoraptor** [comment]
Don't you think library/css/style.css will be confusing and easily mixed up with the default style.css? I couldn't think of a good name, default and classic are both old stylesheet names in library/styles. It's still left from when I thought of style1 and style2, but I agree a better name could be suitable.

And actually superfish is not _that_ bloated. The minified file is 8kb. So I think it's a keeper.

**Comment by JamesGeiger** [comment]
@middlesister we could do main.css

**Comment by falcoraptor** [comment]
So main.css it is. See 5142fbf28
I think 2.0 beta is getting ready to be wrapped up

**Comment by arjhun** [comment]
Just completed dutch translation! How are things going with 2.0?

**Comment by falcoraptor** [comment]
Thanks!

2.0 is shaping up well. I'll be wrapping it up during next week and then send it forward so it can be submitted for review on .org.
