### ISSUE TITLE
Version 2.0 release checklist

### ISSUE THREAD

**Issue by falcoraptor** [ThematicTheme/Thematic#95]
- [x] Update readme.txt and style.css: version number
- [x] Update readme.txt and style.css: stable tag
- [x] Update readme.txt and style.css: tested up to tag
- [x] Update readme.txt and style.css requires tag (will bump to 3.8 after 4.0 is released)
- [x] Update changelog information
- [x] Update translation files
- [x] Final Theme Check test
- [ ] Tag 2.0

**Comment by JamesGeiger** [comment]
@middlesister  There are still some styling issues. I will send you a fix for those tonight.

@scottnix, if you are still alive can you take a look at the new stylesheet if you get a chance?

**Comment by falcoraptor** [comment]
Oh, yes I know. Above all - we have three pull requests waiting for feedback from gene. I am not ready to release anything until he gets a say. He is also the one who has the contact with Ian, and Ian is the only one with access to upload to the wordpress.org repo.

**Comment by JamesGeiger** [comment]
@middlesister I was too tired to look last night, but I will send a pull request in a day or two. Can't you be made the owner of Thematic on wordpress.org? It is kind of silly that Ian has to submit it since he has not worked on it in years.

**Comment by scottnix** [comment]
I have the newest development version setup locally, I will take a look some time today. I will try to test some crossbrowser stuff and check everything out, especially the portions dealing with responsive design. :)

**Comment by JamesGeiger** [comment]
@scottnix cool. I can sleep easier if you look at it lol

**Comment by falcoraptor** [comment]
@SeamlessThemes I know, it's a little frustrating. This is how it's been all these years. Every time a new version is ready we have to send it to Ian for submission. Access to the svn is tied to the .org account that created it.  It _is_ possible to change, but it is apparently not trivial and to convince Otto to do it would not be easy. Besides, if anyone should have that authority it should be Gene and not me. But the reality is that this is Ian's creation and he still has the last word on the project. Which I understand, his name is on it. I too would like to have a say in something that bears my name.

@scottnix oh yes please do! I think the side margins probably should be bigger on tablets/medium screens, but it really is not my strength. I did follow the practice of putting the media queries in the section they apply to instead of in one chunk in the bottom. I like it, I just hope it doesn't become too confusing to read and override.

**Comment by JamesGeiger** [comment]
@middlesister well it might be his, but it is only what it is today because of the community. Also no offense to Gene, but he just disappeared too. It is a volunteer project, but you should at least announce that you are taking a break or something like that. Just my 2 cents.

**Comment by falcoraptor** [comment]
Well you could as well say that I disappeared all summer and autumn too. We all work on it when we have time, it's just not always that our schedules match.

The whole legacy mode structure is his work and without it we couldn't be where we are today. Backwards compatibility is crucial, especially with such a large install base that Thematic has.

**Comment by JamesGeiger** [comment]
@middlesister yes I know he did a lot and I was not trying to put him down, but hey, sometimes you need to point some fingers :D

**Comment by falcoraptor** [comment]
Heh, well I would like to hear from him too so there we agree. :) I have pinged him and am waiting for response. He was working 6-7 days a week in the end of November so I can only hope he has less of a workload now and can spare a moment for Thematic.

**Comment by JamesGeiger** [comment]
@middlesister can we retired the grids folder? I really doubt anyone uses it anymore.

**Comment by JamesGeiger** [comment]
@scottnix did you get a chance to look?

**Comment by scottnix** [comment]
I am a little confused, it doesn't help that I haven't done anything really Thematic related for a while now. Is style1.css loading as kind of a test for development? With style1.css loading that way it will break every existing theme out there if they upgrade, which is why I hope it is a testing thing. ;P
1. Placeholder image for screenshot inside child theme, but for the image put the file name (screenshot.png) and recommended size which is now 880x660 http://codex.wordpress.org/Theme_Development#Screenshot which would serve to speed up development times just by making it that much easier. The original screenshot.png in the parent theme should probably be replaced for a newer one with the new dimensions at the least, in case someone looks at it as a reference.
2. Remove display: inline-block from the .menu-toggle css, the idea is removing it provides a bigger click area that stretches across the available space instead of having to click on the "menu" text. The same issue could be said about the menu list item links, the a (link elements) should also be set to display: block to fill up available space giving more room to click a link.
   - It might also be an idea to add the padding for the sub items that is on the UL to the LI instead, when you add hover effects, like a background hover, you are most likely going to want the hover to affect the whole box. Debatable, it just seems padding on the li instead would be an easier default to work with.
3. Remove font-style: italic from H3, remove text-transform: uppercase from H4, just seems a little odd.
4. Possibly add { cursor: help } to the abbr[title], currently it just has the default cursor. 
5. q (quote element) is not defined with any style https://developer.mozilla.org/en-US/docs/Web/CSS/quotes
6. When you squeeze down the site to where the sidebar first drops down below the content due to the media query taking effect, the alignment of the content and primary sidebar is off, the text from both sections doesn't line up, something like this would be more noticeable when you start adding backgrounds.

**Comment by JamesGeiger** [comment]
@middlesister .page-title needs to be made bigger, right now it is extremely small.

![page-title](https://f.cloud.github.com/assets/1751040/2047795/908cb9f6-8a2c-11e3-85b4-d18587ccc390.jpg)

**Comment by falcoraptor** [comment]
@scottnix Thanks for your list and for checking! I will add these to issue #61 since this is not the place. I realize I have not been consistent in referencing the issue number in my commit messages because if I had, all style related commits would be listed in that issue. Some of these things were already on my list and even fixed very recently.

Regarding the stylesheet, no it's not a testing thing. This stylesheet will be used by default on all new installs. This is the beauty of the dependency filter. In xhtml mode - and all upgraded themes will be in xhtml mode by default - the dependency is removed so this stylesheet will never be enqueued. This filter lives in legacy/legacy.php. The whole file is basically an inverse of my html5 plugin and then some. It will turn almost everything back to the way it was in 1.0.4 with very few exceptions. I tested an upgrade using a github upgrader plugin, and this worked. The old child theme did not break.

For upgrades, the switch to html5 will need to be done manually by checking a check box in the theme options. This way, it's a conscious decision and can be done after or while updating the child theme. One of my biggest tasks is actually writing a transition guide for the docs section, outlining all the changes needed.

@SeamlessThemes yes this is addressed in e819e06a9c06d298e3138fe8bca3c1d25a5bf538

**Comment by AlexWebLab** [comment]
Any idea on when the 2.0 will be released?

**Comment by falcoraptor** [comment]
Not at the moment, no :(
I haven't heard anything from Gene in months and I would like him to check the code before pushing the update. But I will make it as ready as I can, and while I cannot say when the update will be available through the .org repo it will be available to download as beta from here.

**Comment by falcoraptor** [comment]
@alessandroweb Thematic 2.0-beta1 is now tagged and ready for download. Download link is https://github.com/ThematicTheme/Thematic/archive/2.0-beta1.zip
I think it is pretty stable, but please report any issues you have with it. Enjoy! :)

**Comment by JamesGeiger** [comment]
@middlesister @emhr Any new on Thematic 2.0 going live??

**Comment by iCristiano** [comment]
Any news?
